[connections.postgresql]
dialect = "postgresql"
host = "ep-cool-salad-azebuawg-pooler.c-3.ap-southeast-1.aws.neon.tech"
port = 5432
database = "neondb"
username = "neondb_owner"
password = "npg_ZtFEK6dNXYR2"
sslmode = "require"